version: "1"
module_version: 0.0.1
# runner_image: spacelift/runner:latest
# terraform_versions:
#   - "0.12.27"
#   - "0.12.28"

test_defaults:
  before_init: ["terraform fmt -check"]
#   runner_image: spacelift/runner:latest