version: "1"
module_version: 0.0.1
runner_image: spacelift/runner:latest

test_defaults:
  before_init: ["terraform fmt -check"]
#   runner_image: spacelift/runner:latest

tests:
- name: simple-example
  project_root: examples/simple-example